add_newline = false


format = """$username$directory$git_branch$git_status$python$character"""

[username]
style_user = "bold #bbbbbb" # Un gris claro/blanco discreto
style_root = "bold red"
format = "[$user]($style) "
disabled = false 
show_always = true

[directory]
style = "bold white"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "

# 
[git_branch]
symbol = " "
style = "bold #555555"
format = "[$symbol$branch]($style)"

[git_status]
style = "bold #555555"
format = '([\[$all_status$ahead_behind\]]($style)) '


[python]
symbol = "py "
style = "bold #458588"
format = " [($symbol$venv)]($style)"
detect_extensions = []
detect_files = []
detect_folders = []
